In [7]:
using JSON

# Ruta base para los archivos
base_path = ""

# Función para cargar datos JSON desde un archivo
function load_json(file_path)
    open(file_path, "r") do file
        return JSON.parse(file)
    end
end

begin
	base_path = "C:\\Users\\Felipe\\Documents\\003_EXPERIMENTAL_003\\ARC\\"
	training_challenges = load_json(base_path * "arc-agi_training_challenges.json")
	training_solutions = load_json(base_path * "arc-agi_training_solutions.json")
	# evaluation_challenges = load_json(base_path * "arc-agi_evaluation_challenges.json")
	# evaluation_solutions = load_json(base_path * "arc-agi_evaluation_solutions.json")
end

function recall(i, j)
    k = sort(collect(keys(training_challenges)))
    t = k[i] 
    task = training_challenges[t]
    println("Set #", i, ", ", t)
    println("Input:")
    display(task["train"][j]["input"])  # Ajustar el índice para Julia
    println("Output:")
    display(task["train"][j]["output"]) # Ajustar el índice para Julia
end

# recall(5, 1)


recall (generic function with 1 method)

In [10]:
vector_of_arrays = training_challenges[sort(collect(keys(training_challenges)))[5]]["train"][1]["input"]

# Obtener a
a = reduce(vcat, map(row -> reshape(row, 1, :), vector_of_arrays))

# Verificar tipos
println("Tipo de vector_of_arrays: ", typeof(vector_of_arrays))
println("Tipo de a: ", typeof(a))

#training_solutions["a64e4611"]["train"][1]["input"]

Tipo de vector_of_arrays: Vector{Any}
Tipo de a: Matrix{Any}


In [ ]:
rows, cols = size(a)
for i in 1:rows
    for j in 1:cols
        println("row ", i, " || and col ", j)
    end
end

In [1]:
rows, cols = size(a)
ceros = zeros(Float64, rows*3, cols*3)
println(size(ceros))
for i in 1:rows, j in 1:cols

end

UndefVarError: UndefVarError: `a` not defined

In [23]:
struct MatrixAnidada{T<:AbstractMatrix}
    mat1::T
    mat2::T 
    mat3::T
end

In [ ]:
matrix_of_matrices = Array{MatrixTriple{Matrix{Float64}}, 2}(undef, rows, cols)

In [ ]:
for i in 1:rows, j in 1:cols
        matrix_of_matrices[i, j] = MatrixTriple(
            zeros(Float64, 3, 3),  
            zeros(Float64, 5, 5), 
            zeros(Float64, 7, 7)  
        )
    end
end

In [29]:
function create_submatrix(a, i, j, submatrixSize)
    using PaddedViews
    rows, cols = size(a)
    submatrix = fill(0, submatrixSize, submatrixSize)
    reach = (submatrixSize - 1)/2
    enum = -reach:reach
    padded_A = PaddedView(-1, A, (1:reach*2, 1:reach*2), (2:, 2:4))
    for si in enum, sj in enum
            ri = i + si
            cj = j + sj
            if ri >= 1 && ri <= rows && cj >= 1 && cj <= cols
                for 
                submatrix[di + 2, dj + 2] = a[ri, cj]
                elseif
                println("row $i and col $j problem")
        end
    end
    
    return submatrix
end

create_submatrix (generic function with 1 method)

In [ ]:
import Pkg; Pkg.add("PaddedViews")

In [15]:
using PaddedViews

# Example matrix
A = [1 2 3; 4 5 6; 7 8 9]

# Symmetrically pad the matrix with a fill value of -1
padded_A = PaddedView(-1, A, (1:5, 1:5), (2:4, 2:4))

5×5 PaddedView(-1, OffsetArray(::Matrix{Int64}, 2:4, 2:4), (1:5, 1:5)) with eltype Int64 with indices 1:5×1:5:
 -1  -1  -1  -1  -1
 -1   1   2   3  -1
 -1   4   5   6  -1
 -1   7   8   9  -1
 -1  -1  -1  -1  -1

In [18]:
function symmetric_pad(A, pad_size)
    m, n = size(A)
    padded_A = similar(A, m + 2*pad_size, n + 2*pad_size)
    
    for i in 1:m+2*pad_size, j in 1:n+2*pad_size
        padded_A[i,j] = A[clamp(i-pad_size,1,m), clamp(j-pad_size,1,n)]
    end
    
    return padded_A
end

# Example usage
A = [1 2 3; 4 5 6; 7 8 9]
padded_A = symmetric_pad(A, 1)

5×5 Matrix{Int64}:
 1  1  2  3  3
 1  1  2  3  3
 4  4  5  6  6
 7  7  8  9  9
 7  7  8  9  9

In [43]:
A = [1 2 3; 4 5 6; 7 8 9]
submatrixSize=5
m,n=size(A)
pad = div(submatrixSize - 1, 2)  #pad is integer, fill() need that
paddedMatrix = fill(-1,m+pad*2,n+pad*2)
for i in 1:m, j in 1:n
    paddedMatrix[i+pad,j+pad] = A[i,j]
end
display(paddedMatrix)

struct matrixTiles{T<:AbstractMatrix}
    matrices::Vector{T}
end

for i in 1:m+pad, j in 1:n+pad
    submatrix = 

7×7 Matrix{Int64}:
 -1  -1  -1  -1  -1  -1  -1
 -1  -1  -1  -1  -1  -1  -1
 -1  -1   1   2   3  -1  -1
 -1  -1   4   5   6  -1  -1
 -1  -1   7   8   9  -1  -1
 -1  -1  -1  -1  -1  -1  -1
 -1  -1  -1  -1  -1  -1  -1

In [54]:
struct MatrixAnidada{T<:AbstractMatrix}
    matrices::Vector{T}
end

# Example usage:

# Define some matrices of different sizes
mat1 = [1 2; 3 4]
mat2 = [5 6 7; 8 9 10]
mat3 = [11 12; 13 14]
mat4 = [15 16 17 18; 19 20 21 22]
mat5 = [23 24 25; 26 27 28]

# Create instances of MatrixAnidada with different sets of matrices
matrix_set1 = MatrixAnidada([mat1, mat2, mat3])
matrix_set2 = MatrixAnidada([mat4, mat5, mat1])

println(size(matrix_set1))
println(matrix_set2)

MethodError: MethodError: no method matching size(::MatrixAnidada{Matrix{Int64}})

Closest candidates are:
  size(!Matched::BitVector)
   @ Base bitarray.jl:104
  size(!Matched::BitVector, !Matched::Integer)
   @ Base bitarray.jl:107
  size(!Matched::Base.ExceptionStack)
   @ Base errorshow.jl:1018
  ...


In [48]:
struct MatrixAnidada2{T<:AbstractMatrix}
    mat1::T
    mat2::T 
    mat3::T
end

# Example usage:
mat1 = [1 2; 3 4]
mat2 = [5 6; 7 8]
mat3 = [9 10; 11 12]
fixed_matrices = MatrixAnidada2(mat1, mat2, mat3)

println(fixed_matrices.mat1)
println(fixed_matrices.mat2)
println(fixed_matrices.mat3)


[1 2; 3 4]
[5 6; 7 8]
[9 10; 11 12]


In [50]:
struct MatrixAnidada3{T<:AbstractMatrix}
    fixed_matrices::NTuple{3, T}
    variable_matrices::Vector{T}
end
mat1 = [1 2; 3 4]
mat2 = [5 6 7; 8 9 10]
mat3 = [11 12; 13 14]
mat4 = [15 16 17 18; 19 20 21 22]
mat5 = [23 24 25; 26 27 28]
# Example usage:
fixed_matrices = (mat1, mat2, mat4)
variable_matrices = [mat4, mat5]
mixed_matrices = MatrixAnidada3(fixed_matrices, variable_matrices)

println(mixed_matrices.fixed_matrices)
println(mixed_matrices.variable_matrices)


([1 2; 3 4], [5 6 7; 8 9 10], [15 16 17 18; 19 20 21 22])
[[15 16 17 18; 19 20 21 22], [23 24 25; 26 27 28]]


In [56]:
struct MatrixAnidada4{T<:AbstractMatrix}
    matrices::Array{T, 3}
end

# Custom indexing method
function Base.getindex(ma::MatrixAnidada4, i::Int, j::Int, k::Int)
    return ma.matrices[i, j, k]
end

# Custom size method
function Base.size(ma::MatrixAnidada4)
    return size(ma.matrices)
end

# Allow iteration
Base.iterate(ma::MatrixAnidada4) = iterate(ma.matrices)
Base.iterate(ma::MatrixAnidada4, state) = iterate(ma.matrices, state)


In [63]:
mat1 = [1 2; 3 4]
matrix = [1 2.5 "hello"; 4 5.7 "world"; 6 7.8 "$mat1"]

3×3 Matrix{Any}:
 1  2.5  "hello"
 4  5.7  "world"
 6  7.8  "[1 2; 3 4]"

In [ ]:
using Lux, Random

function conv_block(in_channels, out_channels)
    return Chain(
        Conv((3, 3), in_channels => out_channels, pad=(1, 1), stride=(1, 1)),
        BatchNorm(out_channels),
        x -> relu.(x),
        Conv((3, 3), out_channels => out_channels, pad=(1, 1), stride=(1, 1)),
        BatchNorm(out_channels),
        x -> relu.(x)
    )
end

function unet(in_channels, out_channels)
    # Encoder (downsampling)
    enc1 = conv_block(in_channels, 64)
    enc2 = Chain(MaxPool((2, 2)), conv_block(64, 128))
    enc3 = Chain(MaxPool((2, 2)), conv_block(128, 256))
    enc4 = Chain(MaxPool((2, 2)), conv_block(256, 512))

    # Bridge
    bridge = Chain(MaxPool((2, 2)), conv_block(512, 1024))

    # Decoder (upsampling)
    dec4 = Chain(ConvTranspose((2, 2), 1024 => 512, stride=(2, 2)), conv_block(1024, 512))
    dec3 = Chain(ConvTranspose((2, 2), 512 => 256, stride=(2, 2)), conv_block(512, 256))
    dec2 = Chain(ConvTranspose((2, 2), 256 => 128, stride=(2, 2)), conv_block(256, 128))
    dec1 = Chain(ConvTranspose((2, 2), 128 => 64, stride=(2, 2)), conv_block(128, 64))

    # Output layer
    out = Conv((1, 1), 64 => out_channels)

    function forward(x, ps, st)
        # Encoder
        e1 = enc1(x, ps.enc1, st.enc1)
        e2 = enc2(e1, ps.enc2, st.enc2)
        e3 = enc3(e2, ps.enc3, st.enc3)
        e4 = enc4(e3, ps.enc4, st.enc4)

        # Bridge
        b = bridge(e4, ps.bridge, st.bridge)

        # Decoder with skip connections
        d4 = dec4(cat(b, e4, dims=3), ps.dec4, st.dec4)
        d3 = dec3(cat(d4, e3, dims=3), ps.dec3, st.dec3)
        d2 = dec2(cat(d3, e2, dims=3), ps.dec2, st.dec2)
        d1 = dec1(cat(d2, e1, dims=3), ps.dec1, st.dec1)

        # Output
        return out(d1, ps.out, st.out)
    end

    return Chain(forward)
end

# Crear el modelo
rng = Random.default_rng()
model = unet(3, 1)  # 3 canales de entrada, 1 canal de salida

# Inicializar parámetros y estados
dummy_input = randn(rng, 256, 256, 3, 1)  # Entrada de ejemplo: 256x256 imagen RGB
ps, st = Lux.setup(rng, model)

# Realizar una pasada hacia adelante
y, _ = model(dummy_input, ps, st)

println("Forma de la salida: ", size(y))